### PR TITLE
fix(update-expression-builder): index in attribute path

### LINKED ISSUE #200: IncrementBy/decrementBy not working when using array position in attributePath
```typescript
new TransactUpdate(MyModel, partitionKey, rangeKey)
  .operations( update(`myList[0]`).incrementBy(42) )
```

**expected behaviour:**
should generate UpdateExpression as follows:
```javascript
{
   type: 'SET',
   statement: '#myList[0] = #myList[0] + :myList_at_0',
   attributeNames: { '#myList': 'myList' },
   attributeValues: { ':myList_at_0': { N: '42' } },
 }
```

**actual behaviour:**
throws `Error: Given value must be either Array or Set 42`
only updateFunction `set()` works with indexes in attribute path

### PR DESCRIPTION
**Pull request by simonmumenthaler**
closes #200

### CODE REVIEW

File: src/dynamo/expression/update-expression-builder.ts [hunk 1]
```diff
@@ -100,7 +100,7 @@ function buildDefaultExpression(
     // special case: [same as in buildDefaultConditionExpression]
     // we have the metadata for an Array/Set of an Object,
     // but only get a single item when using `attribute('myCollectionProp[0]').set({})`
```
Comment (michaelwittwer) [inline src/dynamo/expression/update-expression-builder.ts]: update comment, not exclusive to ...set() operation
